### PR TITLE
feat: added avatar component

### PR DESCRIPTION
**Pull request by ooreally**
added avatar component to the component library.
Please go through the preview link : https://deploy-preview-3--decora.netlify.app/components/avatar/avatar.html
Here is a screen shot
image

### CODE REVIEW

**Comment by TusharJade** [comment]
Code lools clean just add screenshots of how its looks while rasing pull request or you can deploy your repo on netlify so it will automatically generate a preview

**Comment by ooreally** [comment]
Noted. On it

**Review by vikrantkode — COMMENTED** [review]
- Dont add all the files at once ( you've added empty files also)
- Cant see preview link.

**Comment by ooreally** [comment]
Thanks for your feedback .The preview link is available now @TusharJade @vikrantkode

**Pull request merged**
